routes/web.php
        ->middleware('permission:tiposusuario.show');
    Route::DELETE('tiposusuario/{role}', 'TipoUsuarioController@destroy')->name('tiposusuario.destroy')
        ->middleware('permission:tiposusuario.destroy');
    Route::GET('tiposusuario/{role}/edit', 'TipoUsuarioController@edit')->name('tiposusuario.edit')
        ->middleware('permission:tiposusuario.edit');
    Route::GET('tiposusuario/{role}', 'TipoUsuarioController@show')->name('tiposusuario.show')
        ->middleware('permission:tiposusuario.show');
    Route::GET('tiposusuario/{role}', 'TipoUsuarioController@show')->name('tiposusuario.show')
        ->middleware('permission:tiposusuario.show');

//estado usuarios

    Route::GET('estadosusuario', 'EstadoUsuarioController@index')->name('estadosusuario.index')
        ->middleware('permission:estadosusuario.index');
    Route::POST('estadosusuario', 'EstadoUsuarioController@store')->name('estadosusuario.store')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/create', 'EstadoUsuarioController@create')->name('estadosusuario.create')
        ->middleware('permission:estadosusuario.index');
    Route::post('estadosusuario/{role}', 'EstadoUsuarioController@update')->name('estadosusuario.update')
        ->middleware('permission:estadosusuario.index ');
    Route::GET('estadosusuario/{role}', 'EstadoUsuarioController@show')->name('estadosusuario.show')
        ->middleware('permission:estadosusuario.index');
    Route::DELETE('estadosusuario/{role}', 'EstadoUsuarioController@destroy')->name('estadosusuario.destroy')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/{role}/edit', 'EstadoUsuarioController@edit')->name('estadosusuario.edit')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/{role}', 'EstadoUsuarioController@show')->name('estadosusuario.show')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/active/{role}', 'EstadoUsuarioController@activeUser')->name('estadosusuario.active')->middleware('permission:estadosusuario.active');
    Route::GET('estadosusuario/desactive/{role}', 'EstadoUsuarioController@desactiveUser')->name('estadosusuario.desactive')->middleware('permission:estadosusuario.desactive');    
   //crud    personas
    Route::resource('personas', 'PersonaController')->middleware('permission:personas.index');

// radicados
    Route::GET('radicaciones', 'RadicacionUsuariosController@create')->name('radicaciones.create')
        ->middleware('permission:radicaciones.create');
    Route::POST('radicaciones', 'RadicacionUsuariosController@store')->name('radicaciones.store')
         ->middleware('permission:radicaciones.store');
    Route::GET('radicaciones/{id_radicado}', 'RadicacionUsuariosController@show')->name('radicaciones.show')
    ->middleware('permission:radicaciones.show');  
     Route::GET('radipdf/{id}', 'PdfController@Reporteuno')->name('radipdf.Reporteuno')
    ->middleware('permission:radipdf.Reporteuno');
    Route::GET('radicados/usuarios/asig', 'RadicacionUsuariosController@getRadicados')->name('radicados.getRadicados')
    ->middleware('permission:radicados.getRadicados');
    Route::GET('remitente/personas/asig', 'RadicacionUsuariosController@getRemitente')->name('radicados.getRemitente')
    ->middleware('permission:radicados.getRemitente');
     Route::GET('radicados/asociados/asig', 'RadicacionUsuariosController@getRadicadoAsociado')->name('radicados.getRadicadoAsociado')
    ->middleware('permission:radicados.getRadicadoAsociado');

// formato codigo

     Route::GET('parcod', 'ParaCodigoController@index')->name('parcod.index')
    ->middleware('permission:parcod.index');

    Route::POST('parcod','ParaCodigoController@store')->name('parcod.store')
    ->middleware('permission:parcod.index');



//Route::resource('articles','ArticleController');
    Route::resource('departamentos', 'DepartamentoController')->middleware('permission:departamentos.index');
    Route::resource('ciudades', 'CiudadController')->middleware('permission:departamentos.index');
    Route::resource('tiposidentificacion', 'TipoIdentificacionController')->middleware('permission:tiposidentificacion.index');

    Route::resource('organizaciones', 'OrganizacionController');
    Route::resource('dependencias', 'DependenciaController')->middleware('permission:dependencias.index');
    Route::resource('cargos', 'CargoController');

    Route::resource('rolesusuarios', 'RolUsuarioController');
    Route::resource('tiposaccion', 'TiposAccionController')->middleware('permission:tiposaccion.index');
    Route::resource('sitioradicacion', 'SitioRadicacionController');
    Route::resource('tiposdocumentales', 'TipoDocumentalesController');
    Route::resource('estados', 'EstadosRadicacionController');
    Route::resource('tiporadicacion', 'TipoRadicacionController');
    Route::resource('tiposolicitud', 'TipoSolicitudController');
    Route::resource('tipocourie', 'TipoCourieController');
    
   

 //organizaciones
 
     Route::GET('organizaciones', 'OrganizacionController@index')->name('organizaciones.index')
        ->middleware('permission:organizaciones.index');
    Route::POST('organizaciones', 'OrganizacionController@store')->name('organizaciones.store')
        ->middleware('permission:organizaciones.index');
    Route::GET('organizaciones/create', 'OrganizacionController@create')->name('organizaciones.create')
        ->middleware('permission:organizaciones.index');
    Route::PUT('organizaciones/{organizacione}', 'OrganizacionController@update')->name('organizaciones.update')
        ->middleware('permission:organizaciones.index');
    Route::GET('organizaciones/{organizacione}', 'OrganizacionController@show')->name('organizaciones.show')
        ->middleware('permission:organizaciones.index');
    Route::DELETE('organizaciones/{organizacione}', 'OrganizacionController@destroy')->name('organizaciones.destroy')
        ->middleware('permission:organizaciones.index');
    Route::GET('organizaciones/{organizacione}/edit', 'OrganizacionController@edit')->name('organizaciones.edit')
        ->middleware('permission:organizaciones.index');

        //busqueda de radicados
    Route::GET('radbusqueda', 'BusquedaRadicadosController@index')->name('radbusqueda.index')->middleware('permission:radbusqueda.index');
    Route::GET('radbusqueda.erm','BusquedaRadicadosController@mostrarTabla')->name('radbusqueda.erm')
        ->middleware('permission:radbusqueda.index');

    Route::GET('radbusqueda/{id}', 'BusquedaRadicadosController@show')->name('radbusqueda.show')->middleware('permission:radbusqueda.index'); 
    
    Route::get('documentos/descargar/{type}', 'BusquedaRadicadosController@descargarDocumento');


        //gestion de correspondencia
    Route::GET('correspondencia', 'CorrespondenciaRadicadosController@index')->name('correspondencia.index')->middleware('permission:correspondencia.index');
     Route::GET('correspondencia-admin', 'CorrespondenciaRadicadosController@tablaAdmin')->name('correspondencia.tablaAdmin')->middleware('permission:correspondencia.erm');
    Route::GET('correspondencia.erm','CorrespondenciaRadicadosController@mostrarTabla')->name('correspondencia.erm')->middleware('permission:correspondencia.erm');

    Route::GET('correspondencia.ermadmin','CorrespondenciaRadicadosController@mostrarTablaAdmin')->name('correspondencia.ermadmin')->middleware('permission:correspondencia.erm');
    Route::GET('corresver/{id}', 'CorrespondenciaRadicadosController@show')->name('corebusqueda.show')->middleware('permission:correspondencia.erm');

    Route::GET('corresver/descargar/{id}', 'CorrespondenciaRadicadosController@descargarArchivo')->name('corebusqueda.descargarArchivo')->middleware('permission:corebusqueda.show');

    Route::GET('ejemplo/descargar', 'CorrespondenciaRadicadosController@descargarEjemploArchivo')->name('corebusqueda.descargarArchivo')->middleware('permission:corebusqueda.show');

    Route::GET('coregestion/crear/{id}', 'CorrespondenciaRadicadosController@gestion')->name('gestion.index')->middleware('permission:gestion.index'); 
    Route::POST('coregestion/crear', 'CorrespondenciaRadicadosController@gestionar')->name('gestion.gestionar')->middleware('permission:gestion.index');
    Route::GET('coregestion/ver/{id}', 'CorrespondenciaRadicadosController@showtwo')->name('coregestion.showtwo')->middleware('permission:gestion.index'); 
    Route::GET('coregestion/{id}', 'CorrespondenciaRadicadosController@showmodal')->name('coregestion.modal')->middleware('permission:coregestion.modal');
   
    //perfil
   Route::GET('miperfil', 'perfilController@index')->name('miperfil.index')->middleware('permission:miperfil.index');
   Route::POST('miperfil/update', 'perfilController@update')->name('miperfil.cambiar')->middleware('permission:miperfil.index');

   //documentos 


   Route::GET('documentos/cargar', 'documentosController@cargar')->name('documento.cargar')->middleware('permission:miperfil.index');
   Route::POST('documentos/upload', 'documentosController@upload');
   Route::get('documentos/consulta', 'documentosController@consultaDB');

   //configuracion del sistema

   Route::GET('conf/general','ConfSistemaController@conf')->name('configuracion.sistema')->middleware('permission:configuracion.sistema');
   Route::post('actualizar/general','ConfSistemaController@actualizarConf')->name('actualizar.sistema')->middleware('permission:configuracion.sistema');
});


Route::GET('radiperso', 'RadicacionUsuariosController@emerpersona')->name('radicaciones.vistauno');
Route::GET('radidesti', 'RadicacionUsuariosController@emerdesti')->name('radicaciones.emerdesti');
Route::POST('radicacionesperson', 'RadicacionUsuariosController@storepersona')->name('radicaciones.storepersona');
Route::POST('radicacionesdesti', 'RadicacionUsuariosController@storedesti')->name('radicaciones.storedesti');

resources/views/tiposdocumentales/create.blade.php
@extends('layout')


@section('content')
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Generar Nuevo tipo de documento</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tiposdocumentales.index') }}">Volver</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong>no se pudo generar solicitud.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(array('route' => 'tiposdocumentales.store','method'=>'POST')) !!}
         @include('tiposdocumentales.form')
    {!! Form::close() !!}

@endsection

resources/views/tiposdocumentales/edit.blade.php
@extends('layout')


@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Tipo de documental</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('sitioradicacion.index') }}">Volver</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Suele suceder,por favor verifique.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::model($sradicado, ['method' => 'PUT','route' => ['sitioradicacion.update', $sradicado->id]]) !!}
        @include('sitioradicacion.form')
    {!! Form::close() !!}

@endsection

resources/views/tiposdocumentales/form.blade.php
<div class="row">
    <table WIDTH="1000">
        <tr>
            <td>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Descripcion:</strong>
                        {!! Form::text('TdrDescripcion', null, array('class' => 'form-control')) !!}
                    </div>
                </div>
            </td>
                
        </tr>
         <tr>
            <td>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Sigla:</strong>
                        {!! Form::text('TdrSigla', null, array('class' => 'form-control', 'placeholder'=>'Maximo 3 letras y minusculas','maxlength'=>'3')) !!}
                    </div>
                </div>
            </td>
                
        </tr>
    </table>
     <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Generar</button>
    </div>
</div>

resources/views/tiposdocumentales/index.blade.php
@extends('layout')


@section('content')
 <div class="row" class="controlSidebarOptions" >
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tipos de documentales</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('tiposdocumentales.create') }}">Generar nuevo documento</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="table-responsive" style="overflow: auto">
        <table class="table table-bordered">
            <tr class="thead-inverse" style="font-size:16px">
                <th>id</th>
                <th>Descripcion</th>
                <th>Sigla</th>
                <th width="280px">Operacion</th>
            </tr>
        @foreach ($tiposdocumentales as $dato)
            <tr style="font-size:14px">
                <td>{{ $dato->id}}</td>
                <td>{{ $dato->TdrDescripcion}}</td>
                <td>{{ $dato->TdrSigla}}</td>
               <td>
             {!! Form::open(['method' => 'DELETE','route' => ['tiposdocumentales.destroy', $dato->id],'style'=>'display:inline']) !!}
   {!! Form::submit('Eliminar', ['class' => 'btn btn-danger btn-sm']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </table>
    </div>

@endsection

resources/views/tiposdocumentales/show.blade.php
@extends('layout')


@section('content')
   <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Mostrar Documento</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('personas.index') }}"> volver</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Primer Nombre:</strong>
                {{$persona->primer_nombre}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Segundo Nombre:</strong>
                {{ $persona->segundo_nombre}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Primer Apellido:</strong>
                {{ $persona->primer_apellido}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Segundo Apellido:</strong>
                {{ $persona->segundo_apellido}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Pais</strong>
                {{ $persona->pais_id}}
            </div>
        </div>
    </div>
@endsection