routes/web.php
        ->middleware('permission:tiposusuario.show');
    Route::DELETE('tiposusuario/{role}', 'TipoUsuarioController@destroy')->name('tiposusuario.destroy')
        ->middleware('permission:tiposusuario.destroy');
    Route::GET('tiposusuario/{role}/edit', 'TipoUsuarioController@edit')->name('tiposusuario.edit')
        ->middleware('permission:tiposusuario.edit');
    Route::GET('tiposusuario/{role}', 'TipoUsuarioController@show')->name('tiposusuario.show')
        ->middleware('permission:tiposusuario.show');
    Route::GET('tiposusuario/{role}', 'TipoUsuarioController@show')->name('tiposusuario.show')
        ->middleware('permission:tiposusuario.show');

//estado usuarios

    Route::GET('estadosusuario', 'EstadoUsuarioController@index')->name('estadosusuario.index')
        ->middleware('permission:estadosusuario.index');
    Route::POST('estadosusuario', 'EstadoUsuarioController@store')->name('estadosusuario.store')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/create', 'EstadoUsuarioController@create')->name('estadosusuario.create')
        ->middleware('permission:estadosusuario.index');
    Route::post('estadosusuario/{role}', 'EstadoUsuarioController@update')->name('estadosusuario.update')
        ->middleware('permission:estadosusuario.index ');
    Route::GET('estadosusuario/{role}', 'EstadoUsuarioController@show')->name('estadosusuario.show')
        ->middleware('permission:estadosusuario.index');
    Route::DELETE('estadosusuario/{role}', 'EstadoUsuarioController@destroy')->name('estadosusuario.destroy')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/{role}/edit', 'EstadoUsuarioController@edit')->name('estadosusuario.edit')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/{role}', 'EstadoUsuarioController@show')->name('estadosusuario.show')
        ->middleware('permission:estadosusuario.index');
    Route::GET('estadosusuario/active/{role}', 'EstadoUsuarioController@activeUser')->name('estadosusuario.active')->middleware('permission:estadosusuario.active');
    Route::GET('estadosusuario/desactive/{role}', 'EstadoUsuarioController@desactiveUser')->name('estadosusuario.desactive')->middleware('permission:estadosusuario.desactive');    
   //crud    personas
    Route::resource('personas', 'PersonaController')->middleware('permission:personas.index');

// radicados
    Route::GET('radicaciones', 'RadicacionUsuariosController@create')->name('radicaciones.create')
        ->middleware('permission:radicaciones.create');
    Route::POST('radicaciones', 'RadicacionUsuariosController@store')->name('radicaciones.store')
         ->middleware('permission:radicaciones.store');
    Route::GET('radicaciones/{id_radicado}', 'RadicacionUsuariosController@show')->name('radicaciones.show')
    ->middleware('permission:radicaciones.show');  
     Route::GET('radipdf/{id}', 'PdfController@Reporteuno')->name('radipdf.Reporteuno')
    ->middleware('permission:radipdf.Reporteuno');
    Route::GET('radicados/usuarios/asig', 'RadicacionUsuariosController@getRadicados')->name('radicados.getRadicados')
    ->middleware('permission:radicados.getRadicados');
    Route::GET('remitente/personas/asig', 'RadicacionUsuariosController@getRemitente')->name('radicados.getRemitente')
    ->middleware('permission:radicados.getRemitente');
     Route::GET('radicados/asociados/asig', 'RadicacionUsuariosController@getRadicadoAsociado')->name('radicados.getRadicadoAsociado')
    ->middleware('permission:radicados.getRadicadoAsociado');

// formato codigo

     Route::GET('parcod', 'ParaCodigoController@index')->name('parcod.index')
    ->middleware('permission:parcod.index');

    Route::POST('parcod','ParaCodigoController@store')->name('parcod.store')
    ->middleware('permission:parcod.index');



//Route::resource('articles','ArticleController');
    Route::resource('departamentos', 'DepartamentoController')->middleware('permission:departamentos.index');
    Route::resource('ciudades', 'CiudadController')->middleware('permission:departamentos.index');
    Route::resource('tiposidentificacion', 'TipoIdentificacionController')->middleware('permission:tiposidentificacion.index');

    Route::resource('organizaciones', 'OrganizacionController');
    Route::resource('dependencias', 'DependenciaController')->middleware('permission:dependencias.index');
    Route::resource('cargos', 'CargoController');

    Route::resource('rolesusuarios', 'RolUsuarioController');
    Route::resource('tiposaccion', 'TiposAccionController')->middleware('permission:tiposaccion.index');
    Route::resource('sitioradicacion', 'SitioRadicacionController');
    Route::resource('tiposdocumentales', 'TipoDocumentalesController');
    Route::resource('estados', 'EstadosRadicacionController');
    Route::resource('tiporadicacion', 'TipoRadicacionController');
    Route::resource('tiposolicitud', 'TipoSolicitudController');
    Route::resource('tipocourie', 'TipoCourieController');
    
   

 //organizaciones
 
     Route::GET('organizaciones', 'OrganizacionController@index')->name('organizaciones.index')
        ->middleware('permission:organizaciones.index');
    Route::POST('organizaciones', 'OrganizacionController@store')->name('organizaciones.store')
        ->middleware('permission:organizaciones.index');
    Route::GET('organizaciones/create', 'OrganizacionController@create')->name('organizaciones.create')
        ->middleware('permission:organizaciones.index');
    Route::PUT('organizaciones/{organizacione}', 'OrganizacionController@update')->name('organizaciones.update')
        ->middleware('permission:organizaciones.index');
    Route::GET('organizaciones/{organizacione}', 'OrganizacionController@show')->name('organizaciones.show')
        ->middleware('permission:organizaciones.index');
    Route::DELETE('organizaciones/{organizacione}', 'OrganizacionController@destroy')->name('organizaciones.destroy')
        ->middleware('permission:organizaciones.index');
    Route::GET('organizaciones/{organizacione}/edit', 'OrganizacionController@edit')->name('organizaciones.edit')
        ->middleware('permission:organizaciones.index');

        //busqueda de radicados
    Route::GET('radbusqueda', 'BusquedaRadicadosController@index')->name('radbusqueda.index')->middleware('permission:radbusqueda.index');
    Route::GET('radbusqueda.erm','BusquedaRadicadosController@mostrarTabla')->name('radbusqueda.erm')
        ->middleware('permission:radbusqueda.index');

    Route::GET('radbusqueda/{id}', 'BusquedaRadicadosController@show')->name('radbusqueda.show')->middleware('permission:radbusqueda.index'); 
    
    Route::get('documentos/descargar/{type}', 'BusquedaRadicadosController@descargarDocumento');


        //gestion de correspondencia
    Route::GET('correspondencia', 'CorrespondenciaRadicadosController@index')->name('correspondencia.index')->middleware('permission:correspondencia.index');
     Route::GET('correspondencia-admin', 'CorrespondenciaRadicadosController@tablaAdmin')->name('correspondencia.tablaAdmin')->middleware('permission:correspondencia.erm');
    Route::GET('correspondencia.erm','CorrespondenciaRadicadosController@mostrarTabla')->name('correspondencia.erm')->middleware('permission:correspondencia.erm');

    Route::GET('correspondencia.ermadmin','CorrespondenciaRadicadosController@mostrarTablaAdmin')->name('correspondencia.ermadmin')->middleware('permission:correspondencia.erm');
    Route::GET('corresver/{id}', 'CorrespondenciaRadicadosController@show')->name('corebusqueda.show')->middleware('permission:correspondencia.erm');

    Route::GET('corresver/descargar/{id}', 'CorrespondenciaRadicadosController@descargarArchivo')->name('corebusqueda.descargarArchivo')->middleware('permission:corebusqueda.show');

    Route::GET('ejemplo/descargar', 'CorrespondenciaRadicadosController@descargarEjemploArchivo')->name('corebusqueda.descargarArchivo')->middleware('permission:corebusqueda.show');

    Route::GET('coregestion/crear/{id}', 'CorrespondenciaRadicadosController@gestion')->name('gestion.index')->middleware('permission:gestion.index'); 
    Route::POST('coregestion/crear', 'CorrespondenciaRadicadosController@gestionar')->name('gestion.gestionar')->middleware('permission:gestion.index');
    Route::GET('coregestion/ver/{id}', 'CorrespondenciaRadicadosController@showtwo')->name('coregestion.showtwo')->middleware('permission:gestion.index'); 
    Route::GET('coregestion/{id}', 'CorrespondenciaRadicadosController@showmodal')->name('coregestion.modal')->middleware('permission:coregestion.modal');
   
    //perfil
   Route::GET('miperfil', 'perfilController@index')->name('miperfil.index')->middleware('permission:miperfil.index');
   Route::POST('miperfil/update', 'perfilController@update')->name('miperfil.cambiar')->middleware('permission:miperfil.index');

   //documentos 


   Route::GET('documentos/cargar', 'documentosController@cargar')->name('documento.cargar')->middleware('permission:miperfil.index');
   Route::POST('documentos/upload', 'documentosController@upload');
   Route::get('documentos/consulta', 'documentosController@consultaDB');

   //configuracion del sistema

   Route::GET('conf/general','ConfSistemaController@conf')->name('configuracion.sistema')->middleware('permission:configuracion.sistema');
   Route::post('actualizar/general','ConfSistemaController@actualizarConf')->name('actualizar.sistema')->middleware('permission:configuracion.sistema');
});


Route::GET('radiperso', 'RadicacionUsuariosController@emerpersona')->name('radicaciones.vistauno');
Route::GET('radidesti', 'RadicacionUsuariosController@emerdesti')->name('radicaciones.emerdesti');
Route::POST('radicacionesperson', 'RadicacionUsuariosController@storepersona')->name('radicaciones.storepersona');
Route::POST('radicacionesdesti', 'RadicacionUsuariosController@storedesti')->name('radicaciones.storedesti');

resources/views/tiposidentificacion/create.blade.php
@extends('layout')


@section('content')
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Crear nuevo tipo de identificación</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tiposidentificacion.index') }}"> Volver</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> No se pudo realizar.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(array('route' => 'tiposidentificacion.store','method'=>'POST')) !!}
         @include('tiposidentificacion.form')
    {!! Form::close() !!}

@endsection

resources/views/tiposidentificacion/edit.blade.php
@extends('layout')


@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Tipo de identificacion</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tiposidentificacion.index') }}"> Volver</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> No se pudo realizar.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::model($tipoidentificacion, ['method' => 'PATCH','route' => ['tiposidentificacion.update', $tipoidentificacion->id]]) !!}
        @include('tiposidentificacion.form')
    {!! Form::close() !!}

@endsection

resources/views/tiposidentificacion/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Tipo:</strong>
            {!! Form::text('tipo', null, array('placeholder' => 'tipo','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nombre:</strong>
            {!! Form::text('nombre', null, array('placeholder' => 'Nombre','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Crear</button>
    </div>
</div>

resources/views/tiposidentificacion/index.blade.php
@extends('layout')


@section('content')
 <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tipos Identificacion</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('tiposidentificacion.create') }}"> Crear nuevo tipo de identificacion</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Tipo</th>
            <th>Nombre</th>
            <th width="280px">Operacion</th>
        </tr>
    @foreach ($tiposidentificacion as $tipoidentificacion)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $tipoidentificacion->tipo}}</td>
        <td>{{ $tipoidentificacion->nombre}}</td>
        <td>
            <a class="btn btn-primary" href="{{ route('tiposidentificacion.edit',$tipoidentificacion->id) }}">Editar</a>
            {!! Form::open(['method' => 'DELETE','route' => ['tiposidentificacion.destroy', $tipoidentificacion->id],'style'=>'display:inline']) !!}
            {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </table>
    {!! $tiposidentificacion->render() !!}
@endsection

resources/views/tiposidentificacion/show.blade.php
@extends('layout')


@section('content')
   <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Ver tipo de identificacion</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tiposidentificacion.index') }}"> Vovler</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo:</strong>
                {{$tipoidentificacion->tipo}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                {{ $tipoidentificacion->nombre}}
            </div>
        </div>
    </div>
@endsection